### ISSUE TITLE
Use CamelCase Notation for all the Elements of the benchlow-test

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/test-definition-model#4]
E.g., also for https://github.com/benchflow/test-definition-model/blob/dev/src/test/resources/benchflow-test.yml#L44

This because most of the elements are camelCase. Then think about aligning to the way Docker Compose approach it.

**Comment by simonedavico** [comment]
The `dev` branch is out of date, since its history is broken. 
This has already been taken care of.

**Comment by VincenzoFerme** [comment]
Ok, when you merge the changes, mark this issue as fixed.

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#54
